name: Java CI
on: [push]

jobs:
#  windows-build:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: 8
#          # architecture: 'x86'
#          distribution: 'temurin'
#      - uses: ilammy/msvc-dev-cmd@v1
#      - name: Build with Ant
#        run: ant generate-all compile compile_native
#      - uses: actions/upload-artifact@v3
#        with:
#          name: LWJGL-2-windows-x64
#          path: |
#            libs/*.jar 
#            libs/windows/*
#          if-no-files-found: error
#  linux-build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: 8
#          # architecture: 'x86'
#          distribution: 'temurin'
#      - name: Set up GCC
#        uses: egor-tensin/setup-gcc@v1
#        with:
#          version: latest
#          platform: x64
#      - name: Download X11 development libraries
#        run: sudo apt install libxxf86vm-dev libxrandr-dev libxcursor-dev
#      - name: Build with Ant
#        run: ant generate-all compile compile_native
#      - uses: actions/upload-artifact@v3
#        with:
#          name: LWJGL-2-linux-x64
#          path: |
#            libs/*.jar 
#            libs/linux/*
#          if-no-files-found: error
  mac-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          # architecture: 'x86'
          distribution: 'temurin'
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Build with Ant
        run: ant generate-all compile compile_native
      - uses: actions/upload-artifact@v3
        with:
          name: LWJGL-2-macosx-x64
          path: |
            libs/*.jar 
            libs/macosx/*
          if-no-files-found: error